apiVersion: apps/v1
kind: Deployment
metadata:
  name: previleged-deployment
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: previleged-deployment
  template:
    metadata:
      labels:
        app: previleged-deployment
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        securityContext:
          allowPrivilegeEscalation: true
      - name: sidecar
        image: nginx:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
